export const listbook = [
  {
    rating: 1,
    name: "Theory: Is Alien Real",
    author: "Alan Runner",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    categoryName: "Nature",
    publisher: 'Century ABC (2018)',
  },
  {
    rating: 4,
    name: "Be your self & Never Surrender",
    author: "Jess Steve",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    categoryName: "Biography",
    publisher: 'Garamedia  (2020)',
  },
  {
    rating: 3,
    name: "SAKURA",
    author: "Elsa Max",
    price: "19.99",
    imageUrl: "./static-data/img-none.jpg",
    categoryName: "Biography",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Century ABC (2018)'
  },
  {
    rating: 4,
    name: "SUNGLASES",
    author: "Samuel Lee",
    price: "18.13",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Garamedia  (2020)',
    categoryName: "Nature",
  },
  {
    rating: 5,
    name: "What colors of the sky",
    author: "Lunaric Axe",
    price: "13.77",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Wepress (2020)',
    categoryName: "Nature",
  },
  {
    rating: 4,
    name: "So You Want To Talk About Race",
    author: "Ijeoma Oluo",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Century ABC (2018)',
    categoryName: "Biography",
  },
  {
    rating: 2,
    name: "Life of Wilds",
    author: "Jasmine Belle",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Garamedia  (2020)',
    categoryName: "Biography",
  },
    {
    rating: 1,
    name: "Theory: Is Alien Real",
    author: "Alan Runner",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    categoryName: "Nature",
    publisher: 'Century ABC (2018)',
  },
  {
    rating: 4,
    name: "Be your self & Never Surrender",
    author: "Jess Steve",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    categoryName: "Biography",
    publisher: 'Garamedia  (2020)',
  },
  {
    rating: 3,
    name: "SAKURA",
    author: "Elsa Max",
    price: "19.99",
    imageUrl: "./static-data/img-none.jpg",
    categoryName: "Biography",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Century ABC (2018)'
  },
  {
    rating: 4,
    name: "SUNGLASES",
    author: "Samuel Lee",
    price: "18.13",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Garamedia  (2020)',
    categoryName: "Nature",
  },
  {
    rating: 5,
    name: "What colors of the sky",
    author: "Lunaric Axe",
    price: "13.77",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Wepress (2020)',
    categoryName: "Nature",
  },
  {
    rating: 4,
    name: "So You Want To Talk About Race",
    author: "Ijeoma Oluo",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Century ABC (2018)',
    categoryName: "Biography",
  },
  {
    rating: 2,
    name: "Life of Wilds",
    author: "Jasmine Belle",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    publisher: 'Garamedia  (2020)',
    categoryName: "Biography",
  },
];