export const listbook = [
  {
    rating: 1,
    title: "Theory: Is Alien Real",
    author: "Alan Runner",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Nature",
  },
  {
    rating: 4,
    title: "Be your self & Never Surrender",
    author: "Jess Steve",
    price: "15.63",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Biography",
  },
  {
    rating: 3,
    title: "SAKURA",
    author: "Elsa Max",
    price: "19.99",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Biography",
  },
  {
    rating: 4,
    title: "SUNGLASES",
    author: "Samuel Lee",
    price: "18.13",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Nature",
  },
  {
    rating: 5,
    title: "What colors of the sky",
    author: "Lunaric Axe",
    price: "13.77",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Biography",
  },
  {
    rating: 4,
    title: "So You Want To Talk About Race",
    author: "Ijeoma Oluo",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Nature",
  },
  {
    rating: 2,
    title: "Life of Wilds",
    author: "Jasmine Belle",
    price: "23.44",
    imageUrl: "./static-data/img-none.jpg",
    imageAuthor: "./static-data/img-none.jpg",
    category: "Biography",
  },
];